apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: actionq-server
    kustomize.toolkit.fluxcd.io/name: actionq-server
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: actionq-server
  namespace: vscode
spec:
  clusterIP: 172.17.141.41
  clusterIPs:
  - 172.17.141.41
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: actionq-server
  sessionAffinity: None
  type: ClusterIP

